# roles/pxeserver/tasks/main.yml
---

- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: pxeserver

- name: Install packages
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ pxeserver_packages }}"
  tags: pxeserver

- name: Ensure services are started
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ pxeserver_services }}"
  tags: pxeserver

- name: Create directory for PXEboot related files
  file:
    path: "{{ pxeserver_path }}"
    state: directory
  tags: pxeserver

- name: Make Network Boot Programs for BIOS and UEFI based systems available
  command: cp "{{ item }}" "{{ pxeserver_path }}/{{ item|regex_replace('.*/', '') }}"
  args:
    creates: "{{ pxeserver_path }}/{{ item|regex_replace('.*/', '') }}"
  with_items: "{{ pxeserver_files }}"
  tags: pxeserver

- name: Create directory for PXE server configuration
  file:
    path: "{{ pxeserver_path }}/pxelinux.cfg"
    state: directory
  tags: pxeserver

- name: Create directories for boot images
  file:
    path: "{{ pxeserver_path }}/{{ item.name }}"
    state: directory
  with_items: "{{ pxeserver_images }}"
  tags: pxeserver

- name: Download boot images
  get_url:
    url: "{{ item.kernel_url }}"
    dest: "{{ pxeserver_path }}/{{ item.name }}/vmlinuz"
  with_items: "{{ pxeserver_images }}"
  tags: pxeserver

- name: Download initrd images
  get_url:
    url: "{{ item.initrd_url }}"
    dest: "{{ pxeserver_path }}/{{ item.name }}/initrd.img"
  with_items: "{{ pxeserver_images }}"
  tags: pxeserver

- name: Create default menu for BIOS based systems
  template:
    src: pxelinux.cfg_default
    dest: "{{ pxeserver_path }}/pxelinux.cfg/default"
  tags: pxeserver

- name: DHCP configuration for PXE server
  template:
    src: etc_dhcp_dhcpd-pxelinux.conf.j2
    dest: /etc/dhcpd-pxelinux.conf
    owner: root
    group: root
    mode: '0600'
  notify: restart dhcp
  tags: pxeserver

- name: Copy local kickstart files
  copy:
    src: "{{ item.kickstart_path }}"
    dest: "{{ pxeserver_path }}/{{ item.name }}/ks.cfg"
  when: item.kickstart_path is defined
  with_items: "{{ pxeserver_images }}"
  tags: pxeserver

- name: Download remote kickstart files
  get_url:
    url: "{{ item.kickstart_url }}"
    dest: "{{ pxeserver_path }}/{{ item.name }}/ks.cfg"
  when: item.kickstart_url is defined
  with_items: "{{ pxeserver_images }}"
  tags: pxeserver

- name: Load PXELinux DHCP configuration from main DHCP config file
  lineinfile:
    dest: /etc/dhcp/dhcpd.conf
    line: 'include "/etc/dhcpd-pxelinux.conf";'
  notify: restart dhcp
  tags: pxeserver
